root: 
  - financial_institution:
    name: 'Simplii'
    url: 'https://www.simplii.com/en/rates.html'
    accounts:
      # No Fee Chequing Account
      - account:
        account_name_xpath: '//*[@id="accounts"]/div[1]/div/h4/span/text()'
        account_rates_start: '//*[@id="accounts"]/div[2]/div/div/div/table/tbody/tr[2]/td[1]/p/text()'
        account_rates_end: '//*[@id="accounts"]/div[2]/div/div/div/table/tbody/tr[6]/td[2]/p/text()'
      # High Interest Savings Account
      - account:
        account_name_xpath: '//*[@id="accounts"]/div[5]/div/h4/span/text()'
        account_rates_start: '//*[@id="accounts"]/div[6]/div/div/div/table/tbody/tr[2]/td[1]/p/text()'
        account_rates_end: '//*[@id="accounts"]/div[6]/div/div/div/table/tbody/tr[2]/td[1]/p/text()'
  
  - financial_institution:
    name: 'CIBC'
    url: 'cibc url'
    accounts:
      # Account #1
      - account:
        account_name: 'cibc account'
        account_xpath: 'cibc xpath'
      
      # Account #2
      - account:
        account_name: 'cibc account 2'
        account_xpath: 'cibc xpath 2'
  
  - financial_institution:
    name: 'RBC'
    url: 'rbc url'
    accounts:
      # Account 1
      - account:
        account_name: 'rbc account 1'
        account_xpath: 'rbc account 2'
      # Account #2
      - account: 
        account_name: 'rbc account 2'
        account_xpath: 'rbc xpath 2'
      # Account #3
      - account: 
        account_name: 'rbc account 3'
        account_xpath: 'rbc xpath 3'

  - financial_institution:
    name: 'TD Bank'
    url: 'td bank url'
    accounts:
      # Account 1
      - account:
        account_name: 'td account 1'
        account_xpath: 'td account 2'
      # Account #2
      - account: 
        account_name: 'td account 2'
        account_xpath: 'td xpath 2'
      # Account #3
      - account: 
        account_name: 'td account 3'
        account_xpath: 'td xpath 3'
